-- =============================================
-- Author:		<Pat Relos>
-- Create date: <4-4-2023>
-- Description:	<Payroll Summary Listview Populate>
-- =============================================
CREATE PROCEDURE [dbo].[formspayrollsummarylistview] 

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    select employee_id, 
			dailyrate_payroll, 
            ecolapayroll, 
            seapayroll, 
            ctpapayroll, 
            regularOTrate , 
            legalholidayrate, 
            legalholidayOTrate, 
            specialholidayrate, 
            specialholidayotrate, 
            nightdiffrate, 
            nightdiffOTrate, 
			specialholidaynightdiffrate, 
            SHonRDOTrate, 
            LHonRDOTrate, 
            noofdayswork, 
            basic, 
            overtime_hours, 
            overtime, 
            legalnoworkhours, 
			legalnowork, 
			legalnoworkrate, 
            legalholiday_hours, 
            legalholiday, 
            ecolaperday, 
			seaperday, 
            ctpaperday, 
            legalHolidayOT_Hours, 
            legalHolidayOT, 
            LHONRDOT, 
            LHONRDOThours, 
            Holiday_Special_Hours, 
            Holiday_Special, 
            Holiday_SpecialOT, 
            Holiday_SpecialOT_Hours, 
            LegalHolidayND, 
            LegalHolidayND_Hours, 
            legalholidayNDrate, 
            Holiday_Specialnightdiff, 
            SHONRDOT, 
            SHONRDOThours, 
            Nightdiff, 
            Nightdiff_Hours, 
            SHNightdiffOT, 
            SHNightdiffOT_Hours, 
            regularnightshiftOT, 
            regularnightshiftOT_hours, 
            regularnightshiftOTrate, 
            thirteenmonth, 
            ytdthirteenmonth, 
            thirteenmonthyear, 
            totalsalary, 
            tardiness, 
            tardiness_hours, 
            grossalary, 
            grossamttaxable, 
            adjustment, 
            adjustment2, 
            contributionpagibigEE, 
            contributionpagibigER, 
            contributionSSSEE, 
            contributionSSSER, 
            contributionSSSECC, 
            contributionSSSEEpro, 
            contributionSSSERpro, 
            contributionphilhealthEE, 
            contributionphilhealthER, 
            Wtax, 
            taxstatus, 
            payrollpaytype, 
            payrollatmno, 
            totaldeduction, 
            netamount, 
            other_deduction, 
            totalot, 
            basicforsss, 
            basicforssspro, 
            basicforphil, 
            basicforphilend, 
            grossprevious, 
            noofdayswork2, 
            noofdaysworkecola, 
            SHonRDOThours, 
            LHonRDOThours, 
            RDhours, 
            RD, 
            RDrate, 
            WDOhours, 
            WDO, 
            WDOrate, 
            lhotndh, 
            lhotnd, 
            lhotndrate, 
            shotndh, 
            shotnd, 
            shotndrate, 
            noofhourswork, 
            pcreateddate, 
            pcreatedby, 
            pupdateby, 
            plastupdate, 
            empbankname, 
            empchequeno, 
            empmoneyxfername, 
            empmoneyxferno, 
            nightdifftotal, 
            netamount2, 
            override, 
            nodeduction, 
            proofread, 
            payrollremarks, 
            other_deduction2, 
            idbranchpositionp 
            from payroll_summary
END
